queue: Hosted VS2017
variables: 
  BuildConfiguration: Release

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: test/AzureSign.Core.Tests/AzureSign.Core.Tests.csproj
    arguments: -c $(BuildConfiguration)
  displayName: Run Tests