queue: Hosted VS2017
variables: 
  BuildConfiguration: Release


- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: AzureSignTool.Tests/AzureSignTool.Tests.csproj
    arguments: -c $(BuildConfiguration)
  displayName: Run Tests